const Events = {
    COMPLAIN_CREATED: 'COMPLAIN_CREATED',
    POST_CREATED: 'POST_CREATED',
    POST_UPDATED: 'POST_UPDATED',
    POST_DELETE:  'POST_DELETE',
    USER_CREATED: 'USER_CREATED'
}

export default Events